version: 0.2

## Required environment variables:
# AWS_ACCOUNT_ID=
# IMAGE_REPO_NAME=
# BASE_IMAGE=
# BUCKET=
# FUNCTION_NAME=
# ENV=
# PARAMETER_OVERRIDES="--parameter-overrides LAMBDAROLE=rolename ENV=envname"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - curl -fsSL https://raw.githubusercontent.com/usdot-jpo-codehub/aws-codebuild-extras/master/install >> extras.sh
      - . ./extras.sh
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - CODEBUILD_RESOLVED_SOURCE_VERSION="${CODEBUILD_RESOLVED_SOURCE_VERSION:-$IMAGE_TAG}"
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME"
  build:
    commands:
      - docker build --build-arg BASE_IMAGE=$BASE_IMAGE -t $IMAGE_URI:$IMAGE_TAG .
      - |
        docker run --rm \
          -e "BUCKET=$BUCKET" \
          -e "FUNCTION_NAME=$FUNCTION_NAME" \
          -e "REGION=$AWS_DEFAULT_REGION" \
          -e "ENV=$ENV" \
          -e "PARAMETER_OVERRIDES=$PARAMETER_OVERRIDES" \
          -e "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" \
          -e "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI" \
          -i $IMAGE_URI:$IMAGE_TAG
  post_build:
    commands:
      - |
        if [ "$CODEBUILD_GIT_BRANCH" = "master" ] || [ "$CODEBUILD_GIT_BRANCH" = "development" ]; then
          docker push "$IMAGE_URI:$IMAGE_TAG";
          docker tag "$IMAGE_URI:$IMAGE_TAG" "$IMAGE_URI:latest"
          docker push "$IMAGE_URI:latest";
        fi
